name: Pre-Commit Report

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    
    # Create custom tests to avoid fail!
    #- name: Test with pytest
    #  run: |
    #    pip install pytest
    #    pytest

    # Looks for reveals secrets
    - name: Secret Scan
      uses: max/secret-scan@1.0.0

    - name: Trufflehog Secret Scan
      run: |
        pip install trufflehog
        trufflehog /home/runner/work/CICD-workflow-testing/CICD-workflow-testing
        trufflehog --help
        trufflehog
        trufflehog .

    #- name: Trufflehog Scan
    #  uses: edplato/trufflehog-actions-scan@master